version: "3"
services:
  react-fakeflix:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./src:/app/src"
    # environment:
    #   - REACT_APP_VARIABLE=example
    # env_file:
    #   - "./.env"
